fixing the bug in the filler of DryingDropletStreamingMethod
YMWani/hoomd-blue pull request #9
Opened 2024-01-10 18:05 UTC by kkritikak

Since Filler added earlier in DryingDropletStreamingMethod wasn't working earlier so this pull request is created to
fix that 

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

2024-01-10 18:08 UTC, kkritikak commented on hoomd/mpcd/DryingDropletStreamingMethod.cc
> +    : mpcd::ConfinedStreamingMethod<mpcd::detail::SphereGeometry>(sysdata, cur_timestep, period, phase, std::make_shared<mpcd::detail::SphereGeometry>(R->getValue(cur_timestep), 0.0, bc)),
I am not sure whether this change was needed or if it's  correct or not but without this change the filler doesn't work, the test code shows segmentation fault.

2024-01-11 03:00 UTC, mphoward requested changes
Please have a look at the comments, and let me know if you are still getting errors if you revert some of the changes as suggested.

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/DryingDropletStreamingMethod.cc
> +    : mpcd::ConfinedStreamingMethod<mpcd::detail::SphereGeometry>(sysdata, cur_timestep, period, phase, std::make_shared<mpcd::detail::SphereGeometry>(R->getValue(cur_timestep), 0.0, bc)),
I don't think this change is needed. You should be able to revert it to what was there before (a null pointer).

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/DryingDropletStreamingMethod.h
> +        std::shared_ptr<mpcd::detail::SphereGeometry> m_geom;                                            //!< Streaming geometry
`m_geom` is already declared in the base class. I don't know what repeating it here does, but at best it's redundant.
```suggestion
```

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/DryingDropletStreamingMethodGPU.cc
> +    : mpcd::ConfinedStreamingMethodGPU<mpcd::detail::SphereGeometry>(sysdata, cur_timestep, period, phase, std::make_shared<mpcd::detail::SphereGeometry>(R->getValue(cur_timestep), 0.0, bc)),
Revert here too.

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/DryingDropletStreamingMethodGPU.h
> +        std::shared_ptr<mpcd::detail::SphereGeometry> m_geom;                                               //!< Streaming geometry
```suggestion
```

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/Integrator.cc
> +    bool checkcollide = checkCollide(timestep);
Use underscore to make more readable.
```suggestion
    bool check_collide = checkCollide(timestep);
```
This also needs to move above, before line 73, and replace **all** calls to `checkCollide` with `check_collide`.

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/Integrator.cc
>      if (checkCollide(timestep) && !m_fillers.empty())
```suggestion
    if (check_collide && !m_fillers.empty())
```

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/Integrator.cc
> +            }
I think it is safe to just call this even if there aren't virtual particles.
```suggestion
        m_mpcd_sys->getParticleData()->removeVirtualParticles();
```

2024-01-11 03:00 UTC, mphoward commented on hoomd/mpcd/test-py/stream_drying_droplet_test.py
> +        mpcd.collide.srd(seed=1221, angle=130., period=1, kT=1.0, group=all_)
I don't think you need to embed any particles in the collision to test the filler, do you?
```suggestion

        mpcd.collide.srd(seed=1221, angle=130., period=1, kT=1.0)
```

2024-01-11 12:41 UTC, kkritikak commented on hoomd/mpcd/test-py/stream_drying_droplet_test.py
> +        mpcd.collide.srd(seed=1221, angle=130., period=1, kT=1.0, group=all_)
Oops, yess this this is not needed

2024-01-11 12:43 UTC, kkritikak commented
Thanks! I made the changes according to the review and after making these changes the test-code is working fine(it's not giving any error)

2024-01-11 14:29 UTC, mphoward approved these changes
Please fix these two minor cosmetic things, and then this is good to merge! I assume it is working for you now in your simulations?

2024-01-11 14:29 UTC, mphoward commented on hoomd/mpcd/DryingDropletStreamingMethod.cc
> +     */
This extended comment is no longer needed since the logic here is simpler now:
```suggestion
// validate geometry
```

2024-01-11 14:29 UTC, mphoward commented on hoomd/mpcd/Integrator.cc
>      // remove any leftover virtual particles
I like to keep code that belongs together grouped under comments:
```suggestion
    // remove any leftover virtual particles
    bool check_collide = checkCollide(timestep);
```

2024-01-11 17:27 UTC, kkritikak commented
Thanks! I fixed those 2 cosmetic things and Yess I checked it for my simulations and this is working fine

2024-02-07 17:20 UTC, merged